// AUTO-GENERATED by scripts/generate-evidence-catalog.mjs — DO NOT EDIT.
// Source of truth: shared/frameworks/soc2_controls.yaml + shared/frameworks/evidence-vocabulary.json.
// Regenerate with: npm run generate:evidence  (CI verifies freshness via check:evidence)

export interface Soc2ControlOption {
  id: string;
  title: string;
  /** Canonical evidence types the scoring engine accepts for this control. */
  types: string[];
}

export const SOC2_CONTROLS: Soc2ControlOption[] = [
  { id: "CC1.1", title: "CC1.1 - Control Environment", types: ["policy_document","security_policies","training_records"] },
  { id: "CC1.2", title: "CC1.2 - Board Independence", types: ["audit_reports","policy_document"] },
  { id: "CC1.3", title: "CC1.3 - Management Philosophy", types: ["policy_document","training_records"] },
  { id: "CC2.1", title: "CC2.1 - Communication and Information", types: ["policy_document","training_records"] },
  { id: "CC2.2", title: "CC2.2 - Information Quality", types: ["audit_reports","policy_document"] },
  { id: "CC2.3", title: "CC2.3 - External Communication", types: ["audit_reports","policy_document"] },
  { id: "CC3.1", title: "CC3.1 - Risk Assessment Process", types: ["audit_reports","policy_document"] },
  { id: "CC3.2", title: "CC3.2 - Risk Identification", types: ["audit_reports","policy_document"] },
  { id: "CC3.3", title: "CC3.3 - Risk Analysis", types: ["audit_reports","policy_document"] },
  { id: "CC4.1", title: "CC4.1 - Monitoring Activities", types: ["audit_reports","event_logs"] },
  { id: "CC4.2", title: "CC4.2 - Separate Evaluations", types: ["audit_reports","policy_document"] },
  { id: "CC5.1", title: "CC5.1 - Control Activities", types: ["audit_reports","policy_document"] },
  { id: "CC5.2", title: "CC5.2 - Control Activities Development", types: ["audit_reports","policy_document"] },
  { id: "CC6.1", title: "CC6.1 - Logical Access Controls", types: ["access_logs","network_configs","system_configs","user_provisioning"] },
  { id: "CC6.2", title: "CC6.2 - Authentication", types: ["system_configs","user_provisioning"] },
  { id: "CC6.3", title: "CC6.3 - Authorization", types: ["policy_document","user_provisioning"] },
  { id: "CC7.1", title: "CC7.1 - System Operations", types: ["event_logs","system_configs"] },
  { id: "CC8.1", title: "CC8.1 - Change Management", types: ["audit_reports","policy_document"] },
  { id: "CC9.1", title: "CC9.1 - Risk Mitigation", types: ["audit_reports","policy_document"] },
  { id: "A1.1", title: "A1.1 - Availability Policies and Procedures", types: ["backup_logs","incident_reports","system_configs"] },
  { id: "A1.2", title: "A1.2 - Capacity Management", types: ["backup_logs","policy_document"] },
  { id: "A1.3", title: "A1.3 - Backup and Recovery", types: ["system_configs"] },
  { id: "A1.4", title: "A1.4 - Incident Response", types: ["backup_logs","policy_document"] },
  { id: "A1.5", title: "A1.5 - System Performance Monitoring", types: ["event_logs","system_configs"] },
  { id: "A2.1", title: "A2.1 - Environmental Controls", types: ["audit_reports","policy_document"] },
  { id: "A2.2", title: "A2.2 - Facility Access", types: ["access_logs","audit_reports"] },
  { id: "A3.1", title: "A3.1 - Network Security", types: ["firewall_configs","network_configs"] },
  { id: "A3.2", title: "A3.2 - Firewall Management", types: ["firewall_configs","network_configs"] },
  { id: "C1.1", title: "C1.1 - Confidentiality Policies", types: ["policy_document","system_configs"] },
  { id: "C1.2", title: "C1.2 - Data Classification", types: ["encryption_policies","system_configs"] },
  { id: "C1.3", title: "C1.3 - Encryption Controls", types: ["audit_reports","policy_document"] },
  { id: "C1.4", title: "C1.4 - Data Masking", types: ["audit_reports","policy_document"] },
  { id: "C2.1", title: "C2.1 - Confidentiality Agreements", types: ["audit_reports","policy_document"] },
  { id: "C2.2", title: "C2.2 - Data Retention", types: ["audit_reports","policy_document"] },
  { id: "C2.3", title: "C2.3 - Data Disposal", types: ["audit_reports","policy_document"] },
  { id: "C3.1", title: "C3.1 - Third Party Confidentiality", types: ["audit_reports","policy_document"] },
  { id: "C3.2", title: "C3.2 - Confidentiality Monitoring", types: ["audit_reports","event_logs"] },
  { id: "PI1.1", title: "PI1.1 - Processing Integrity Controls", types: ["audit_reports","policy_document"] },
  { id: "PI1.2", title: "PI1.2 - Quality Assurance", types: ["audit_reports","system_configs"] },
  { id: "PI1.3", title: "PI1.3 - Input Validation", types: ["audit_reports","event_logs"] },
  { id: "PI1.4", title: "PI1.4 - Processing Controls", types: ["audit_reports","policy_document"] },
  { id: "PI1.5", title: "PI1.5 - Output Validation", types: ["audit_reports","event_logs"] },
  { id: "PI2.1", title: "PI2.1 - Error Handling", types: ["audit_reports","event_logs"] },
  { id: "PI2.2", title: "PI2.2 - Transaction Integrity", types: ["event_logs","system_configs"] },
  { id: "PI3.1", title: "PI3.1 - Processing Monitoring", types: ["audit_reports","event_logs"] },
  { id: "PI3.2", title: "PI3.2 - Exception Reporting", types: ["audit_reports","event_logs"] },
  { id: "CA1.1", title: "CA1.1 - Confidentiality and Availability Management", types: ["audit_reports","policy_document"] },
  { id: "CA1.2", title: "CA1.2 - Incident Response", types: ["incident_reports","policy_document"] },
  { id: "CA1.3", title: "CA1.3 - Security Awareness Training", types: ["security_policies","training_records"] },
  { id: "CA1.4", title: "CA1.4 - Physical Security", types: ["audit_reports","policy_document"] },
  { id: "CA1.5", title: "CA1.5 - Vendor Management", types: ["audit_reports","policy_document"] },
  { id: "CA1.6", title: "CA1.6 - Change Management", types: ["audit_reports","policy_document"] },
  { id: "CA1.7", title: "CA1.7 - Business Continuity", types: ["backup_logs","policy_document"] },
  { id: "CA1.8", title: "CA1.8 - Security Monitoring", types: ["event_logs","system_configs"] },
];

export interface CanonicalEvidenceType {
  description: string;
  category: string;
  aliases: string[];
}

export const CANONICAL_EVIDENCE_TYPES: Record<string, CanonicalEvidenceType> = {
  "access_logs": {"description":"Access/authentication log records (e.g., login activity, access attempts).","category":"SystemLogs","aliases":[]},
  "audit_reports": {"description":"Audit records/reports: review results, audit trail evidence, independent assessment artifacts.","category":"Documents","aliases":["update_status"]},
  "backup_logs": {"description":"Backup and restore records (success/failure, retention).","category":"BackupFiles","aliases":[]},
  "encryption_policies": {"description":"Encryption configuration and policy evidence (at-rest/in-transit encryption, key management).","category":"SecurityPolicies","aliases":["s3_encryption","s3_public_access","iam_mfa"]},
  "event_logs": {"description":"System/event/audit log evidence from the endpoint or cloud.","category":"SystemLogs","aliases":["event_logs"]},
  "firewall_configs": {"description":"Firewall state and rule configuration evidence.","category":"ConfigFiles","aliases":["firewall"]},
  "incident_reports": {"description":"Incident/breach reports and response records.","category":"Documents","aliases":["incident_reports"]},
  "network_configs": {"description":"Network configuration evidence (interfaces, segmentation, routing).","category":"NetworkConfigs","aliases":["network"]},
  "policy_document": {"description":"Written policy/standard/procedure documents.","category":"Documents","aliases":["policy_document"]},
  "security_policies": {"description":"Security configuration/policy evidence from the endpoint (password policy, audit policy, hardening).","category":"SecurityPolicies","aliases":["security_policies","security_settings"]},
  "system_configs": {"description":"System/OS configuration evidence (services, installed software, file permissions, system info).","category":"ConfigFiles","aliases":["system_info","services","software","file_permissions"]},
  "training_records": {"description":"Security awareness/competency training records.","category":"Documents","aliases":["training_records"]},
  "user_provisioning": {"description":"User account/provisioning evidence (account inventory, MFA enforcement, access reviews).","category":"Documents","aliases":["users","iam_policy","iam_mfa"]},
};

/** Map a canonical evidence type to its desktop storage category. */
export function getCategoryForType(evidenceType: string): string {
  return CANONICAL_EVIDENCE_TYPES[evidenceType]?.category ?? "Documents";
}
