// AUTO-GENERATED by scripts/generate-evidence-catalog.mjs — DO NOT EDIT.
// Source of truth: shared/frameworks/soc2_controls.yaml + shared/frameworks/evidence-vocabulary.json.
// Regenerate with: npm run generate:evidence  (CI verifies freshness via check:evidence)

export interface Soc2ControlOption {
  id: string;
  title: string;
  /** Canonical evidence types the scoring engine accepts for this control. */
  types: string[];
}

export const SOC2_CONTROLS: Soc2ControlOption[] = [
  { id: "CC1.1", title: "CC1.1 - Integrity and Ethical Values", types: ["policy_document","training_records"] },
  { id: "CC1.2", title: "CC1.2 - Board Oversight and Independence", types: ["audit_reports","policy_document"] },
  { id: "CC1.3", title: "CC1.3 - Organizational Structure and Reporting Lines", types: ["policy_document"] },
  { id: "CC1.4", title: "CC1.4 - Commitment to Competence", types: ["policy_document","training_records"] },
  { id: "CC1.5", title: "CC1.5 - Individual Accountability", types: ["policy_document"] },
  { id: "CC2.1", title: "CC2.1 - Quality of Information", types: ["policy_document"] },
  { id: "CC2.2", title: "CC2.2 - Internal Communication", types: ["policy_document","training_records"] },
  { id: "CC2.3", title: "CC2.3 - External Communication", types: ["policy_document"] },
  { id: "CC3.1", title: "CC3.1 - Objectives Specification", types: ["audit_reports","policy_document"] },
  { id: "CC3.2", title: "CC3.2 - Risk Identification and Analysis", types: ["audit_reports","policy_document"] },
  { id: "CC3.3", title: "CC3.3 - Fraud Consideration", types: ["audit_reports","policy_document"] },
  { id: "CC3.4", title: "CC3.4 - Change Risk Assessment", types: ["audit_reports","policy_document"] },
  { id: "CC4.1", title: "CC4.1 - Ongoing and Separate Evaluations", types: ["audit_reports","event_logs"] },
  { id: "CC4.2", title: "CC4.2 - Evaluation and Communication of Deficiencies", types: ["audit_reports","incident_reports"] },
  { id: "CC5.1", title: "CC5.1 - Selection of Control Activities", types: ["audit_reports","policy_document"] },
  { id: "CC5.2", title: "CC5.2 - General Controls over Technology", types: ["audit_reports","policy_document"] },
  { id: "CC5.3", title: "CC5.3 - Deployment Through Policies and Procedures", types: ["policy_document"] },
  { id: "CC6.1", title: "CC6.1 - Logical Access Security", types: ["policy_document","security_policies","system_configs"] },
  { id: "CC6.2", title: "CC6.2 - User Registration and Credential Management", types: ["policy_document","user_provisioning"] },
  { id: "CC6.3", title: "CC6.3 - Access Authorization and Modification", types: ["policy_document","user_provisioning"] },
  { id: "CC6.4", title: "CC6.4 - Physical Access Restrictions", types: ["policy_document"] },
  { id: "CC6.5", title: "CC6.5 - Disposal of Physical Assets", types: ["policy_document"] },
  { id: "CC6.6", title: "CC6.6 - Protection Against External Threats", types: ["firewall_configs","network_configs","system_configs"] },
  { id: "CC6.7", title: "CC6.7 - Restriction of Information Transmission", types: ["encryption_policies","network_configs"] },
  { id: "CC6.8", title: "CC6.8 - Unauthorized and Malicious Software Controls", types: ["event_logs","system_configs"] },
  { id: "CC7.1", title: "CC7.1 - Configuration and Vulnerability Detection", types: ["event_logs","system_configs"] },
  { id: "CC7.2", title: "CC7.2 - Anomaly Monitoring", types: ["audit_reports","event_logs"] },
  { id: "CC7.3", title: "CC7.3 - Security Event Evaluation", types: ["audit_reports","incident_reports"] },
  { id: "CC7.4", title: "CC7.4 - Incident Response", types: ["incident_reports","policy_document"] },
  { id: "CC7.5", title: "CC7.5 - Recovery from Security Incidents", types: ["backup_logs","incident_reports"] },
  { id: "CC8.1", title: "CC8.1 - Change Management", types: ["audit_reports","policy_document"] },
  { id: "CC9.1", title: "CC9.1 - Business Disruption Risk Mitigation", types: ["backup_logs","policy_document"] },
  { id: "CC9.2", title: "CC9.2 - Vendor and Business Partner Risk", types: ["audit_reports","policy_document"] },
  { id: "A1.1", title: "A1.1 - Processing Capacity Management", types: ["audit_reports","system_configs"] },
  { id: "A1.2", title: "A1.2 - Environmental Protections, Backup, and Recovery Infrastructure", types: ["backup_logs","system_configs"] },
  { id: "A1.3", title: "A1.3 - Recovery Plan Testing", types: ["audit_reports","backup_logs"] },
  { id: "C1.1", title: "C1.1 - Identification and Maintenance of Confidential Information", types: ["policy_document"] },
  { id: "C1.2", title: "C1.2 - Disposal of Confidential Information", types: ["audit_reports","policy_document"] },
  { id: "PI1.1", title: "PI1.1 - Processing Information Quality", types: ["audit_reports","policy_document"] },
  { id: "PI1.2", title: "PI1.2 - Input Completeness and Accuracy", types: ["audit_reports","policy_document"] },
  { id: "PI1.3", title: "PI1.3 - System Processing Controls", types: ["event_logs","policy_document"] },
  { id: "PI1.4", title: "PI1.4 - Output Delivery", types: ["audit_reports","policy_document"] },
  { id: "PI1.5", title: "PI1.5 - Storage of Inputs and Outputs", types: ["audit_reports","policy_document"] },
];

export interface CanonicalEvidenceType {
  description: string;
  category: string;
  aliases: string[];
}

export const CANONICAL_EVIDENCE_TYPES: Record<string, CanonicalEvidenceType> = {
  "access_logs": {"description":"Access/authentication log records (e.g., login activity, access attempts).","category":"SystemLogs","aliases":[]},
  "audit_reports": {"description":"Audit records/reports: review results, audit trail evidence, independent assessment artifacts.","category":"Documents","aliases":["update_status"]},
  "backup_logs": {"description":"Backup and restore records (success/failure, retention).","category":"BackupFiles","aliases":[]},
  "encryption_policies": {"description":"Encryption configuration and policy evidence (at-rest/in-transit encryption, key management).","category":"SecurityPolicies","aliases":["s3_encryption","s3_public_access","iam_mfa"]},
  "event_logs": {"description":"System/event/audit log evidence from the endpoint or cloud.","category":"SystemLogs","aliases":["event_logs"]},
  "firewall_configs": {"description":"Firewall state and rule configuration evidence.","category":"ConfigFiles","aliases":["firewall"]},
  "incident_reports": {"description":"Incident/breach reports and response records.","category":"Documents","aliases":["incident_reports"]},
  "network_configs": {"description":"Network configuration evidence (interfaces, segmentation, routing).","category":"NetworkConfigs","aliases":["network"]},
  "policy_document": {"description":"Written policy/standard/procedure documents.","category":"Documents","aliases":["policy_document"]},
  "security_policies": {"description":"Security configuration/policy evidence from the endpoint (password policy, audit policy, hardening).","category":"SecurityPolicies","aliases":["security_policies","security_settings"]},
  "system_configs": {"description":"System/OS configuration evidence (services, installed software, file permissions, system info).","category":"ConfigFiles","aliases":["system_info","services","software","file_permissions"]},
  "training_records": {"description":"Security awareness/competency training records.","category":"Documents","aliases":["training_records"]},
  "user_provisioning": {"description":"User account/provisioning evidence (account inventory, MFA enforcement, access reviews).","category":"Documents","aliases":["users","iam_policy","iam_mfa"]},
};

/** Map a canonical evidence type to its desktop storage category. */
export function getCategoryForType(evidenceType: string): string {
  return CANONICAL_EVIDENCE_TYPES[evidenceType]?.category ?? "Documents";
}
