"""add_license_tier_to_users

Revision ID: ea55dc1219d7
Revises: 99f5c91a02f7
Create Date: 2026-04-16 16:43:27.274817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea55dc1219d7'
down_revision: Union[str, None] = '99f5c91a02f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license_tier', sa.String(), server_default='free', nullable=False))
    op.add_column('users', sa.Column('license_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_key')
    op.drop_column('users', 'license_tier')
    # ### end Alembic commands ###
